[eksctl]
version="0.6.0"
tarpath="https://github.com/weaveworks/eksctl/releases/download/${version}/eksctl_${os}_${goarch}.tar.gz"

[jk]
version="0.3.0"
binarypath="https://github.com/jkcfg/jk/releases/download/${version}/jk-${goos}-${goarch}"

[footloose]
version="0.6.3"
binarypath="https://github.com/weaveworks/footloose/releases/download/${version}/footloose-${version}-${os}-${arch}"
tarpath="https://github.com/weaveworks/footloose/releases/download/${version}/footloose-${version}-${os}-${arch}.tar.gz"

[ignite]
version="0.7.0"
binarypath="https://github.com/weaveworks/ignite/releases/download/v${version}/ignite-${goarch}"

[controller]
version="v0.8.3"

